---

- name: install grafana
  ansible.builtin.package:
    name: grafana
    state: present
  tags: installation

- name: start and enable grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  tags: configuration