---

- name: Import grafana GPG public key
  rpm_key:
    key: "{{ grafana_gpg_key_url }}"
    state: present
  tags: installation

- name: copy grafana.repo
  ansible.builtin.copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    owner: bin
    group: wheel
    mode: '0644'
  tags: installation
  
- name: install grafana
  ansible.builtin.package:
    name: grafana
    state: present
  tags: installation

- name: start and enable grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  tags: configuration