---
- name: install mimir
  ansible.builtin.package:
    name: mimir
    state: present
  tags: installation

- name: ensure block storage base folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: '0644'
    
- name: ensure tsdb folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}/{{ mimir_tsdb_folder }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: '0644'

- name: ensure tsdb-sync folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}/{{ mimir_bucket_store_sync_folder }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: '0644'
    
- name: ensure compactor folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}/{{ mimir_compactor_folder }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: '0644'
    
- name: ensure ruler storage folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}/{{ mimir_ruler_storage_folder }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: '0644'

- name: copy config template to mimir folder
  template:
    src: mimir_config.yml.j2
    dest: "{{ mimir_config_path }}"
  tags: installation

- name: Start and enable mimir
  systemd:
    name: mimir
    state: restarted
    enabled: yes
  tags: configuration
