---
- name: install mimir
  ansible.builtin.package:
    name: mimir
    state: present
  tags: installation

- name: stop mimir service
  systemd:
    name: mimir
    state: stopped
  tags: installation
  
- name: ensure block storage base folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: 0755
    
- name: ensure tsdb folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}/{{ mimir_tsdb_folder }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: 0755

- name: ensure alertmanager folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}/{{ mimir_alertmanager_folder }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: 0755
    
- name: ensure compactor folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}/{{ mimir_compactor_folder }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: 0755
    
- name: ensure ruler folder exists
  ansible.builtin.file:
    path: "{{ mimir_block_storage_base_path }}/{{ mimir_ruler_folder }}"
    state: directory
    owner: "{{ mimir_user }}"
    group: "{{ mimir_group }}"
    mode: 0755

- name: copy mimir config
  template:
    src: mimir_config.yml.j2
    dest: "{{ mimir_config_path }}"
  tags: installation
  
- name: copy alertmanager config
  template:
    src: alertmanager-fallback-config.yaml.j2
    dest: "{{ mimir_alertmanager_config_path }}"
  tags: installation

- name: reload mimir service
  systemd:
    name: mimir
    state: reloaded
  tags: configuration
  
- name: restart mimir service
  systemd:
    name: mimir
    state: restarted
    enabled: yes
  tags: configuration
